version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysql-db:/var/lib/mysql
  backend:
    stdin_open: true
    tty: true
    depends_on:
      - db
    build:
      context: ./infra/backend/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    command: bash -c "bundle install && rails server -b 0.0.0.0"
  frontend:
    build:
      context: ./infra/frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/app:/usr/src/app
    command: 'yarn dev'
    ports:
      - 8000:3000
volumes:
  mysql-db:
    driver: local