FROM --platform=linux/x86_64 nginx:latest

# へルスチェック用
RUN apt-get update && apt-get install -y curl vim sudo openssl lsof net-tools apache2-utils

# nginxのインクルードを削除
RUN rm /etc/nginx/conf.d/*

# nginxの設定ファイルをコピー
ADD ./infra/web/default.conf  /etc/nginx/app.conf

# ssl設定
RUN mkdir /etc/nginx/ssl
RUN openssl genrsa -out /etc/nginx/ssl/server.key 2048
RUN openssl req -new -key /etc/nginx/ssl/server.key -out /etc/nginx/ssl/server.csr -subj "/C=JP/ST=Kanagawa/L=Kawasaki/O=ExampleOrganization/CN=localhost"
RUN openssl x509 -in /etc/nginx/ssl/server.csr -days 365 -req -signkey /etc/nginx/ssl/server.key > /etc/nginx/ssl/server.crt
RUN echo /etc/nginx/ssl/server.key > /etc/nginx/ssl/server.password

# Basic認証
RUN htpasswd -b -c /etc/nginx/.htpasswd test test1test1 

# ビルド完了後に実行するコマンド
CMD /usr/sbin/nginx -g 'daemon off;' -c /etc/nginx/app.conf

# ポート開放
EXPOSE 80